#### Problem III.1.1

\begin{align*}
(I-uv^T)^{-1} &=  I + uv^T + uv^Tuv^T + uv^Tuv^Tuv^T + \dots\\
&= I + u (1 + v^Tu + v^Tuv^Tu + \dots ]v^T \\
&= I + u \frac{1}{1-v^Tu}v^T\\
&= I +  \frac{uv^T}{1-v^Tu}\\
\end{align*}

#### Problem III.1.2

* From equation (4), we have $E^{-1} = \begin{bmatrix}I & -uD^{-1} \\ 0 & D^{-1} \end{bmatrix} \begin{bmatrix} I & 0 \\ -v^T & 1 \end{bmatrix} = \begin{bmatrix}I + uD^{-1}v^T & - uD^{-1} \\ -D^{-1}v^T & D^{-1}\end{bmatrix}$

* From equation (5), we have 

$E^{-1} = \begin{bmatrix}(I-uv^T)^{-1} & 0 \\ -v^T(I-uv^T)^{-1} & 1 \end{bmatrix} \begin{bmatrix} I & -u \\ 0 & 1 \end{bmatrix} = \begin{bmatrix}(I-uv^T)^{-1} & -(I-uv^T)^{-1}u \\ -v^T(I-uv^T)^{-1} & 1+v^T(I-uv^T)^{-1}u\end{bmatrix}$

We compare the 1,1 blocks to find $M^{-1} = (I-uv^T)^{-1}$ in formula (1).

#### Problem III.1.3

When $k=1$, we have $M^{-1} = (A-uv^T)^{-1} = A^{-1} + A^{-1}u(I-v^TA^{-1}u)^{-1}v^TA^{-1}$

When $A=\begin{bmatrix}3 & 0 \\ 0 & 2 \end{bmatrix}$, we have $A^{-1} = \begin{bmatrix}\frac{1}{3} & 0 \\ 0 & \frac{1}{2} \end{bmatrix}$, so $(A-uv^T) = \begin{bmatrix}2 & 0 \\ 0 & 2 \end{bmatrix}$, then $(A-uv^T)^{-1} = \begin{bmatrix}\frac{1}{2} & 0 \\ 0 & \frac{1}{2} \end{bmatrix}$.

According to the formula, we have

\begin{align*}
I-v^TA^{-1}u = I - \begin{bmatrix}1 & 0 \end{bmatrix}\begin{bmatrix}\frac{1}{3} & 0 \\ 0 & \frac{1}{2} \end{bmatrix}\begin{bmatrix}1 \\ 0 \end{bmatrix} = \frac{2}{3}
\end{align*}

\begin{align*}
(A-uv^T)^{-1} &= \begin{bmatrix}\frac{1}{3} & 0 \\ 0 & \frac{1}{2} \end{bmatrix} + \begin{bmatrix}\frac{1}{3} & 0 \\ 0 & \frac{1}{2} \end{bmatrix}\begin{bmatrix}1 \\ 0 \end{bmatrix}\frac{3}{2}\begin{bmatrix}1 & 0 \end{bmatrix} \begin{bmatrix}\frac{1}{3} & 0 \\ 0 & \frac{1}{2} \end{bmatrix} \\
&= \begin{bmatrix}\frac{1}{2} & 0 \\ 0 & \frac{1}{2} \end{bmatrix} \\
\end{align*}

These two results agree with each other.

#### Problem III.1.4

We have $Ax=b$, $Az=u$ and $D=1-v^Tz$, set $y=x + \frac{v^Tx}{D}z$, then we have

\begin{align*}
My &= (A-uv^T)y \\
&= (A-uv^T)(x + \frac{v^Tx}{D}z) \\ 
&= Ax + A\frac{v^Tx}{D}z - uv^Tx - uv^T\frac{v^Tx}{D}z\\
&= b + \frac{v^TxAz}{D} - uv^Tx - uv^T\frac{v^Tx}{D}z\\
&= b + \frac{v^Txu}{D} - uv^Tx- uv^T\frac{v^Tx}{D}z\\
&= b + uv^Tx(\frac{1}{D}-1-v^T\frac{1}{D}z)\\
&= b\\
\end{align*}

#### Problem III.1.5

Multiply $A-UV^T$ with formula (9), we have

\begin{align*}
(A-UV^T)M^{-1} &= (A-UV^T)\left(A^{-1} + A^{-1}U(I-V^TA^{-1}U)^{-1}V^TA^{-1}\right)\\
&= (A-UV^T)A^{-1}+(A-UV^T)A^{-1}U(I-V^TA^{-1}U)^{-1}V^TA^{-1}\\
&= (A-UV^T)A^{-1}+(I-UV^TA^{-1})U(I-V^TA^{-1}U)^{-1}V^TA^{-1}\\
&= (A-UV^T)A^{-1}+U(I-V^TA^{-1}U)(I-V^TA^{-1}U)^{-1}V^TA^{-1}\\
&= (A-UV^T)A^{-1}+UV^TA^{-1}\\
&= I - UV^TA^{-1}+UV^TA^{-1}\\
&= I\\
\end{align*}

Where we have used the fourth identity on page 163.

#### Problem III.1.6

When $U=V=I_n$, equation (9) gives formula $(A-I)^{-1} = A^{-1} + A^{-1}(I-A^{-1})^{-1}A^{-1}$

We have $(A-I)^{-1} = \left(A - AA^{-1}\right)^{-1} = \left(A(I - A^{-1})\right)^{-1} = (I - A^{-1})^{-1}A^{-1} =(I-A^{-1} + A^{-1}) (I - A^{-1})^{-1}A^{-1} = A^{-1} + A^{-1} (I - A^{-1})^{-1}A^{-1} $

#### Problem III.1.7

$y = M^{-1}b = \left(A^{-1}+A^{-1}U(I-V^TA^{-1}U)^{-1}V^TA^{-1}\right)b = A^{-1}b + A^{-1}U(I-V^TA^{-1}U)^{-1}V^TA^{-1}b = x + A^{-1}U(I-V^TA^{-1}U)^{-1}V^Tx = x + Z(I-V^TZ)^{-1}V^Tx = x + ZC^{-1}V^Tx = x + Zw$

#### Problem III.1.8

$(A+\Delta A)^2 - A^2 = (A+\Delta A)(A+\Delta A) - A^2 = A\Delta A + \Delta A A + \Delta^2A$, divide by $\Delta t$ and send $\Delta$ to 0, we have $\frac{dA^2(t)}{dt} = A \frac{dA(t)}{dt} + \frac{dA(t)}{dt} A$

#### Problem III.1.9
$\frac{dA(t)}{dt} = \begin{bmatrix}0 & 2t \\ 0 & 0 \end{bmatrix}$
$A^{-1}(t) = \begin{bmatrix}1 & -t^2 \\ 0 & 1 \end{bmatrix}$, by taking derivative directly on $A^{-1}$, we have 

$\frac{dA^{-1}(t)}{dt} = \begin{bmatrix}0 & -2t \\ 0 & 0 \end{bmatrix}$

Using formula (12), we have 

$\frac{dA^{-1}(t)}{dt} = -A^{-1}\frac{dA(t)}{dt}A^{-1} = -\begin{bmatrix}1 & -t^2 \\ 0 & 1 \end{bmatrix}  \begin{bmatrix}0 & 2t \\ 0 & 0 \end{bmatrix} \begin{bmatrix}1 & -t^2 \\ 0 & 1 \end{bmatrix} = \begin{bmatrix}0 & -2t \\ 0 & 0 \end{bmatrix}$

#### Problem III.1.10

It's easy to check that the formula is correct.

#### Problem III.1.11

With $F=1$, divide both sides of those three equations by $\sigma, s, \sigma$, we have

$\begin{bmatrix}\frac{1}{\sigma} & 0\\ -\frac{1}{s}  & \frac{1}{s} \\ 0 & \frac{1}{\sigma}\end{bmatrix} \begin{bmatrix} x_0 \\ x_1 \end{bmatrix} = \begin{bmatrix} \frac{b_0}{\sigma} \\ 0 \\ \frac{b_1}{\sigma} \end{bmatrix}$



$A^T=\begin{bmatrix}\frac{1}{\sigma} & -\frac{1}{s} & 0 \\ 0 & \frac{1}{s} & \frac{1}{\sigma}\end{bmatrix}$, 

so $A^TA = \begin{bmatrix}\frac{1}{\sigma^2}+ \frac{1}{s^2}& -\frac{1}{s^2} \\ -\frac{1}{s^2}& \frac{1}{\sigma^2}+ \frac{1}{s^2}\end{bmatrix}$

$(A^TA)^{-1} = \frac{\sigma^2}{\frac{1}{\sigma^2}+\frac{2}{s^2}}\begin{bmatrix}\frac{1}{\sigma^2}+ \frac{1}{s^2}& \frac{1}{s^2} \\ \frac{1}{s^2}& \frac{1}{\sigma^2}+ \frac{1}{s^2}\end{bmatrix}$

So $x = (A^TA)^{-1}A^Tb = \frac{\sigma^2}{\frac{1}{\sigma^2}+\frac{2}{s^2}}\begin{bmatrix}\frac{1}{\sigma^2}+ \frac{1}{s^2}& \frac{1}{s^2} \\ \frac{1}{s^2}& \frac{1}{\sigma^2}+ \frac{1}{s^2}\end{bmatrix}\begin{bmatrix}\frac{1}{\sigma} & -\frac{1}{s} & 0 \\ 0 & \frac{1}{s} & \frac{1}{\sigma}\end{bmatrix}\begin{bmatrix} \frac{b_0}{\sigma} \\ 0 \\ \frac{b_1}{\sigma} \end{bmatrix} = \frac{1}{\frac{1}{\sigma^2}+\frac{2}{s^2}}\begin{bmatrix}b_0(\frac{1}{\sigma^2}+ \frac{1}{s^2}) + b_1\frac{1}{s^2}\\ b_0\frac{1}{s^2} + b_1(\frac{1}{\sigma^2}+ \frac{1}{s^2})\end{bmatrix} $

So it says $\hat{x}_0$ has more weight to $b_0$, while $\hat{x}_1$ has more weight to $b_1$.

#### Problem III.2.1

Since $u^Tu=1$, take derivative w.r.t. $t$, we have $\frac{d{u^Tu}}{dt} = 0$, we compute the left hand side as :

\begin{align*}
d(u^Tu) &= (u+\Delta u)^T(u+\Delta u) - u^Tu \\
&= u^T\Delta u + \Delta u^T u \\
&= 2u^T\Delta u\\
\end{align*}

Divide both sides by $t$ we have $\frac{d{u^Tu}}{dt} = 2u^T\frac{d\Delta u}{dt} = 0$

So the velocity vector $\frac{du}{dt}$ is orthogonal to the position $u$.

#### Problem III.2.2

Let $A=S+uu^T$ and $B=A+vv^T$, also, let the eigenvalues of $A$ be $z_1 \ge z_2 \ge \dots \ge z_n$. 

So we have $z_1 \ge \lambda_1 \ge z_2 \ge \dots \ge z_n \ge \lambda_n$. We also have

$\alpha_1 \ge z_1 \ge \alpha_2 \ge z_2 \ge \dots \ge \alpha_n \ge z_n$.

For $2\le i \le n$, we have $\alpha_{i-1} \ge z_{i-1} \ge \lambda_{i-1} \ge z_i \ge \alpha_{i+1}$, so in the end we have

$\alpha_1 \ge \lambda_1 \ge \alpha_3 \ge \lambda_3 \ge \alpha_5 \ge \dots \lambda_{n-2} \ge \alpha_n \ge \lambda_n$ and 
$\alpha_2 \ge \lambda_2 \ge \alpha_4 \ge \lambda_4 \ge \alpha_6 \ge \dots \lambda_{n-2} \ge \alpha_n \ge \lambda_n$

#### Problem III.2.3

* (a) We have the eigenvalues of $A(t)$ as: $\lambda_1 = 1+t + \sqrt{1+(1+t)^2}, \lambda_2 = 1 + t - \sqrt{1+(1+t)^2}$

* (b) At $t=0$, $A(0) = \begin{bmatrix}2 & 1 \\ 1 & 0 \end{bmatrix}$, the eigenvalues are $\lambda_1 = 1+\sqrt{2}, \lambda_2=1-\sqrt{2}$. The eigenvectors are: $x_1 = \begin{bmatrix}1+\sqrt{2}\\1\end{bmatrix}, x_2 = \begin{bmatrix}1-\sqrt{2}\\1\end{bmatrix}$. 

For $y^TA(0) = \lambda y^T$, we have the same eigenvectors. To satisfy $y^Tx=1$, we set $y_1 = \frac{1}{4+2\sqrt{2}}\begin{bmatrix}1+\sqrt{2}\\1\end{bmatrix}, y_2 = \frac{1}{4+2\sqrt{2}}\begin{bmatrix}1-\sqrt{2}\\1\end{bmatrix}$

$\frac{d\lambda}{dt} = \begin{bmatrix}1 + \frac{1+t}{\sqrt{(1+t)^2+1}} \\1 - \frac{1+t}{\sqrt{(1+t)^2+1}} \end{bmatrix}$.
At $t=0$, we have $\frac{d\lambda}{dt} = \begin{bmatrix}1 + \frac{1}{\sqrt{2}} \\1 - \frac{1}{\sqrt{2}} \end{bmatrix}$

Now compute $\frac{dA}{dt}= \begin{bmatrix}1 & 1 \\ 1 & 1 \end{bmatrix}$, so we have

\begin{align*}
y^T\frac{dA}{dt}x &= \frac{1}{4+2\sqrt{2}}\begin{bmatrix} 1+\sqrt{2} & 1\end{bmatrix} \begin{bmatrix}1 & 1 \\ 1 & 1 \end{bmatrix} \begin{bmatrix} 1+\sqrt{2} \\ 1 \end{bmatrix}\\
&= 1 + \frac{\sqrt{2}}{2}\\
\end{align*}

This agrees with $\frac{d\lambda}{dt}$

* (c) $A(t) - A(0) = t\begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}$, it has eigenvalues $\lambda_1 = 0, \lambda_2 = 2t$, which are both $\ge 0$ when $t\ge 0$. So the change matrix is semidefinite. 

It's easy to see that $\lambda_1(t)  =1+t + \sqrt{1+(1+t)^2} \ge 1+\sqrt{2} = \lambda_1(0) \ge 0 \ge \lambda_2(t) = 1+t - \sqrt{1+(1+t)^2} \ge \lambda_2(0) = 1-\sqrt{2} $

#### Problem III.2.4

The saddle points occur at the other eigenvectors $q_2$ to $q_{n-1}$ of $S$. To acheive $\lambda_i$ for $\frac{x^TSx}{x^Tx}$ for $x$ in $Y$, we need to choose eigenvectors from $q_1,q_2,\dots,q_i$.

#### Problem III.2.5

* Eigenvalues of $A_1$: $\lambda^1_1 = 1$. 
* Eigenvalues of $A_2$: $\lambda^2_1 = \frac{3+\sqrt{5}}{2},\lambda^2_2 = \frac{3-\sqrt{5}}{2}$, $\lambda^2_1 \ge \lambda^1_1 \ge \lambda^2_2$
* Eigenvalues of $A_3$: $\lambda^3_1 = 3, \lambda^3_2 = 1, \lambda^3_3 = 0$, $\lambda^3_1 \ge \lambda^2_1 \ge \lambda^3_2 \ge \lambda^2_2 \ge \lambda^3_2$

#### Problem III.2.6

* (1) Let $A=D + tS$, at $t=0$, we have $A(0) = D$, and $\frac{d\lambda}{dt} = y^T(0)\frac{dA(0)}{dt}x(0)$.

For $A(0)=D$, we see its eigenvalues are $\lambda_i = i$, where $i=1,2,\dots, n$. We can easily solve for eigenvectors $x_i = \begin{bmatrix}0 \\ 0 \\ \vdots \\ 1 \\ 0 \\ \vdots \\0\end{bmatrix}$ where the 1 is on the $i$th position for $i=1,2,\dots, n$. And $y^T_i = \begin{bmatrix}0 & 0 & \dots & 1 & 0 & \dots &0\end{bmatrix}$.

So for a given $\lambda_i=i$, we have $\frac{d\lambda}{dt} = \begin{bmatrix}0 & 0 & \dots & 1 & 0 & \dots &0\end{bmatrix} S \begin{bmatrix}0 \\ 0 \\ \vdots \\ 1 \\ 0 \\ \vdots \\0\end{bmatrix} = S_{ii}$

The derivatives at $t=0$ of the eigenvalues $\lambda(t)$ of $A$ is just the diagonal entries of $S$.

* (2) When $t$ is small and $t>0$, $A=D+tS$, the eigenvalues of $D$ are just $1,2,\dots,n$, so the eigenvalues of $A$ interlace with eigenvalues of $D$. 

* (3) For any $t>0$, We apply Weyl inequalities, i.e. 
$\lambda_{min}(D+tS) = \lambda_n(D+tS) \le \lambda_n(D) + \lambda_1(tS) = 1 + t\lambda_1(S)$, The last step comes from $S=Q\Lambda Q^T$ because it's symmetric positive definite.
And $\lambda_{min}(D+tS) = \lambda_n(D+tS) \ge \lambda_n(D) + \lambda_n(tS)= 1 + t\lambda_n(S)$

Similarly we have $\lambda_{max}(D+tS) = \lambda_1(D+tS) \ge \lambda_1(D) + \lambda_n(tS)= n + t\lambda_n(S)$ and $\lambda_{max}(D+tS) = \lambda_1(D+tS) \le \lambda_1(D) + \lambda_1(tS) = n + t\lambda_1(S)$


#### Problem III.2.7

* (1) The derivative of a singular value is $\frac{d\sigma}{dt} = u^T(t)\frac{dA}{dt}v(t)$, so we have 

$\frac{dA(0)}{dt} = A$, At $t=0$, we have the matrix $D+tA = D$, so we here look for the singular values and vectors of $D$.

Since $D=IDI$, its singular values are: $1,2,\dots,n$, the left and right singular vectors are $x_i = (0,0,\dots, 1, 0, \dots, 0)$ where the 1 is at the $i$th position. 

So at a singular value $\sigma_i=i$, we have $\frac{d\sigma}{dt} = \begin{bmatrix}0 & \dots & 1 & 0 & \dots & 0\end{bmatrix} A \begin{bmatrix}0 \\ \vdots \\ 1 \\ 0 \\ \vdots \\ 0\end{bmatrix} = A_{ii}$. 

The derivative at $t=0$ of the singular values $\sigma(t)$ is the diagonal values of $A$.

* (2) From Weyl's inequalities we have $\sigma_{max}(D+tA) = \sigma_1(D+tA) \le \sigma_1(D)+\sigma_1(tA) = n + t\sigma_1(A)$

and $\sigma_{min}(D+tA) = \sigma_n(D+tA) \le \sigma_i(D)+\sigma_j(tA) = (n+1-i) + t\sigma_j(A)$. Also we need $i+j=n+1$, so 
 $\sigma_{min}(D+tA) \le (n+1-i) + t\sigma_j(A) = j + t\sigma_j(A)$
 
 #### Problem III.2.8
 
 * (a) Because subspace $V$ has a dimension of $i$, and subpsace $Z$ has a dimension of $n-i+1$, they must have an intersection, otherwise let $p=\sum^i_{k=1} a_kv_k$ a vector in $V$ and $q=\sum^n_{k=i} b_kq_k$ a vector in $Z$, if $V$ and $Z$ doesn't intersect, $v_k$ and $q_k$ are all independent of each other, so we'll have $p+q = \sum^{n+1}_{k=1} c_k x_k$, This contradicts with the fact that there are only $n$ independent basises in total. 
 
 Since $V$ intersect with $Z$, it means that there's a nonzero vector $z$ both in $V$ and $Z$, such that $z$ can be expressed as a combination of $q_i,q_{i+1},\dots, q_n$.
 
 * (b) If $\lambda_i$ is the eigenvalue corresponds to the $i$th large eigenvalue of $S$, since $z$ is also in the subspace of $Z$, where the maximum eigenvalue is $\lambda_i$, so we must have $\frac{z^TSz}{z^Tz} \le \lambda_i$. 
 
 Then $\underset{z\,in\,V}{\min}= \frac{z^TSz}{z^Tz}$ indicates that for any $i$-dimensional subspace $V$, the mimimum value can range from $\lambda_n,\lambda_{n-1},\dots, \lambda_i$ because you can choose any $i$ eigenvectors to compose such space $V$. 
 
 If we then take the maximum among the $i$-dimensional subspace $V$, we see that the maximum value we can achieve is $\lambda_i$.
 
#### Problem III.2.9
 
We have $S=LDL^T$, so $D$ is diagonal and thus symmetric, $L$ is lower triangular matrix, which is invertible, so we see that $S$ is a congruent matrix to $D$. Apply the "Law of Inertia", we can say that $S$ and $D$ have the same number of positive/negative/zero eigenvalues. On the other side, we know that the eigenvalues of $D$ are actually the elements on its diagonal, i.e. the pivots of $S$.

So we conclude that the signs of the pivots of $S$ (in $D$) match the signs of the eigenvalues of $S$.

#### Problem III.2.10

We decompose $H$ into a format of $LDL^T$, that is $H=\begin{bmatrix}S & C \\ C^T & 0 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ C^TS^{-1} & 1 \end{bmatrix}\begin{bmatrix} S & 0 \\ 0 & -C^TS^{-1}C \end{bmatrix}\begin{bmatrix}1 & S^{-1}C \\ 0  & 1 \end{bmatrix}$
So the matrix $D=\begin{bmatrix} S & 0 \\ 0 & -C^TS^{-1}C \end{bmatrix}$, which has $n$ positive pivots and $n$ negative pivots coming from $-C^TS^{-1}C$. According to prlbem 9, we see that the eigenvalues of $H$ match the signs of pivots in $H$, i.e. $D$.

#### Problem III.2.11

Since $S$ is positive definite (symmetric), we have $S=Q\Sigma Q^T$, and $Q^{-1}=Q^T$, all diagonal entries in $\Sigma$ are positive. So we have $S^{-1} = Q\Sigma^{-1}Q^T$, $S^{-1}$ is still a positive definite matrix. So for any $x\ne 0$, we have $-x^TAS^{-1}A^Tx = -(A^Tx)^TS^{-1}(A^Tx)= -b^TS^{-1}b \lt 0$, so $-AS^{-1}A^T$ is negative definite. Note we used the constraint that $Ax=b$

Then the last $m$ pivots of $H$ are negative.

#### Problem III.2.12

We have $(Cy)^TS(Cy) = z^TSz$, where $z=Cy$, since $y\ne 0$, and $C$ is invertible, so $C$ has full rank, and $Cy\ne 0$, so by the definition of positive definite matrix $S$, we have $z^TSz \gt 0$.

#### Problem III.3.1

$AK=\begin{bmatrix}Ab & A^2b & \dots & A^nb\end{bmatrix}$, and $KB = \begin{bmatrix}b & Ab & \dots & A^{n-1}b\end{bmatrix} B = bB_{1,} + AbB_{2,} + \dots + A^{n-1}B_{n,} = \begin{bmatrix}Ab & A^2b & \dots & A^{n-1}b & -b\end{bmatrix}$

So $C=AK-KB = \begin{bmatrix}0 & 0 & \dots & A^nb + b\end{bmatrix}$

#### Problem III.3.2

$(AH)_{ij} = \sum_k A_{ik}H_{kj} = A_{ii}H_{ij} = \frac{2i-1}{2} \frac{1}{i+j-1} = \frac{2i-1}{2(i+j-1)}$
$(HA)_{ij} = \sum_k H_{ik}A_{kj} = H_{ij}A_{jj} = \frac{1}{i+j-1}\frac{2j-1}{2}= \frac{2j-1}{2(i+j-1)}$

So we have $(AH)_{ij} + (HA)_{ij} = \frac{2i-1}{2(i+j-1)} + \frac{2j-1}{2(i+j-1)} = \frac{2(i+j-1)}{2(i+j-1)} = 1$

Whereas $C=AH-HB=AH+HA$, so $C$ are all ones.

#### Problem III.3.3

$AT = \begin{bmatrix}0 & 0 & 0 & 0 &\dots & 0 \\t_0 & t_{-1} & 0 & 0 & \dots & 0 \\t_1 & t_0 & t_{-1} & 0 & \dots & 0\\ 0 & t_1 & t_0 & t_{-1} & 0 & \dots \\ 0 & 0 & \dots & \dots & \dots & \dots\\ 0 & 0 & \dots & t_1 & t_0 & t_{-1}\end{bmatrix}$

$TA^T = \begin{bmatrix}0 & t_0 & t_{-1} & 0 &\dots & 0 \\0 & t_1 & t_0 & t_{-1} & \dots & 0 \\0 & 0 & t_1 & t_0 & t_{-1} & \dots \\ 0 & 0 & \dots & \dots & \dots & \dots\\  0 & 0 & 0 & \dots & t_1 & t_0 \\ 0 & 0 & \dots & 0 & 0 & t_1\end{bmatrix}$


So we have $C=AT-TA^T = \begin{bmatrix}0 & -t_0 & -t_{-1} & 0 &\dots & 0 \\t_0 & t_{-1}-t_1 & -t_0 & -t_{-1} & \dots & 0 \\t_1 & t_0 & t_{-1}-t_1 & -t_0 & -t_{-1} & \dots \\ 0 & 0 & \dots & \dots & \dots & \dots\\  0 & 0 & 0 & \dots & t_{-1}-t_1 & -t_0 \\ 0 & 0 & \dots & t_1 & t_0 & t_{-1}-t_1\end{bmatrix}$

#### Problem III.3.4

$K=U\Sigma \bar{V}^T$, and $\bar{K}^T = V\Sigma \bar{U}^T$ where $\bar{U}^TU=\bar{V}^TV=I$, so we have $H=\bar{K}^TK=V\Sigma \bar{U}^TU\Sigma \bar{V}^T = V\Sigma^2 \bar{V}^T$, the eigenvalues of $H$ is thus $\Sigma^2$, so $\sigma_i(H)=|\sigma_i(K)|^2$ and the singular values of $H$ decay quickly because $K$'s eigenvalues decay quickly from the "Sylvester test"

#### Problem III.3.5

$(AP)_{ij} = \sum A_{ik}P_{kj} = A_{ii}P_{ij} = x_i \frac{s_i+s_j}{x_i+x_j}$ and $(PA)_{ij} = \sum P_{ik}A_{kj} = P_{ij}A_{jj} = x_j \frac{s_i+s_j}{x_i+x_j}$, so we have

$C = AP-P(-A) = AP + PA$ and its elements are $C_{ij} = (AP)_{ij} + (PA)_{ij} = \frac{(x_i+x_j)(s_i+s_j)}{x_i+x_j} = s_i + s_j$

In the end $C=s1^T + 1s^T$, which has rank-2.

#### Problem III.3.6 TODO

If $X$ is invertible, and $AX-XB=C$, we have $AXXX^{-1} - X^{-1}XXB=A'X^{-1} - X^{-1}B' = C$
Since $X$ is invertible, we have $\bar{AXX}^TAXX = \bar{X}^T\bar{X}^T\bar{A}AXX = $

#### Problem III.3.7

Since $A=Q\Lambda Q^{-1}$, so we have $Q^{-1}=\bar{Q}^T$.

$\bar{A}^TA = (\bar{Q}\bar{\Lambda}Q^T)^TQ\Lambda \bar{Q}^T = Q \bar{\Lambda}^T\bar{Q}^TQ\Lambda \bar{Q}^T = Q \bar{\Lambda}\Lambda \bar{Q}^T = Q |{\Lambda}|^2 \bar{Q}^T$

$A\bar{A}^T = Q\Lambda \bar{Q}^T(\bar{Q}\bar{\Lambda}Q^T)^T = Q\Lambda \bar{Q}^TQ \bar{\Lambda}^T\bar{Q}^T = Q\Lambda\bar{\Lambda}\bar{Q}^T = Q |{\Lambda}|^2 \bar{Q}^T$

So $\bar{A}^TA =A\bar{A}^T $

#### Problem III.3.8 TODO

$\bar{A}^TA = (\bar{S}+\bar{Z})^T(S+Z) = (\bar{S}^T+\bar{Z}^T)(S+Z) = \bar{S}^TS + \bar{S}Z + \bar{Z}^TS + \bar{Z}^TZ = \bar{S}S + \bar{S}Z - \bar{Z}S - \bar{Z}Z$

$A\bar{A}^T = (S+Z)(\bar{S}+\bar{Z})^T = (S+Z)(\bar{S}^T+\bar{Z}^T) = S\bar{S}^T + Z\bar{S}^T + Z\bar{Z}^T + S\bar{Z}^T = S\bar{S} + Z\bar{S} - S\bar{Z} - Z\bar{Z}$

#### Problem III.3.9 TODO

#### Problem III.4.1

We minimize $f(x) = x^Tx + \lambda(x^Tv-1)$, take derivative w.r.t. $x$ and set it equal to 0, we have $\frac{df}{dx} = 2x + \lambda v = 0$, so $x = -\frac{1}{2}\lambda v$, take $x^Tv=1$, we have $\lambda = -\frac{2}{|v|^2}$, so the optimal $x=\frac{v}{|v|^2}$

#### Problem III.4.2 TODO

We follow the example 1, where the set $K$ is $x^Tv=1$, which is a closed convex set. Let's rewrite this as a minimizationof $g$. We assume a new function $g(z)$, which is an indicator function of the set $x^Tv=1$, $g(z)=0$ or $g(z) = +\infty$ for $z$ in or out of $x^Tv=1$. 

So the problem changes to 

\begin{align*}
\text{Minimize}\;\; f(x)+g(z)\;\;\text{subject to}\;\; x-z=0\\
\end{align*}

So our scaled augmented Lagrangian is 
\begin{align*}
L_{\rho}(x,z,u) &= \|x\|^2 + g(z) + \frac{1}{2}\rho\|x-z+u\|^2\\
\end{align*}

If we start with $x_0=0,z_0=0,u_0=0$, then we have 

* $x_1 = \text{argmin} [|x|^2 + \frac{1}{2}\rho\|x-z_0+u_0\|^2] = \text{argmin}[\|x\|^2+\frac{1}{2}\rho\|x\|^2] =\text{argmin}[(1+\frac{1}{2}\rho)\|x\|^2]$
  * Solve for the minimal, we find $x_1 = 0$
* $z_1 = \text{projection of}\;x_1 + u_0\;\text{onto }K$, since $x_1 + u_0 = 0$, we find $z_1 = 0$
* $u_1 = u_0 + x_1 - z_1 = 0$

It seems that if we start with $x=z=u=0$, the ADMM won't find the solution. Is this right? 

#### Problem III.4.3

We have Lagrangian as $L(x,y) = \lambda\|x\|_1 + y(x^Tw-1)$ where $w=(2,3)$, assume $x=(x_1,x_2)$, we have 
$L(x,y) = \lambda(|x_1| + |x_2|) + y(2x_1 + 3x_2 -1)$. Take derivatives of $L(x,y)$ w.r.t. $x_1,x_2, y$, we have

* $\frac{\partial{L}}{\partial{x_1}} = \lambda x_1 + 2y = 0$ when $x_1 > 0$
* $\frac{\partial{L}}{\partial{x_2}} = \lambda x_2 + 3y = 0$ when $x_2 > 0$
* $\frac{\partial{L}}{\partial{y}} = 2x_1 + 3x_2 - 1 = 0$

Solve the equations we find $x_1 = \frac{2}{13}, x_2 = \frac{3}{13}$


#### Problem III.4.4

We assume a new function $g(z)$ along with constraint $x-z=0$, where $g(z) = 0$ when $z$ is in the set $z^Tw=1$ and $g(z)=\infty$ when $z$ is out of $z^Tw=1$.

Following example 2, we split the problem into two functions:
* $f_1(x_1) = \lambda|x_1| + \frac{1}{2}\rho(x_1 - v_1)^2$ with $v_1 = z_1 - u_1$
* $f_2(x_2) = \lambda|x_2| + \frac{1}{2}\rho(x_2 - v_2)^2$ with $v_2 = z_2 - u_2$

From example 2, we have the solution 
$x^*_i = v_i(1 - \frac{\lambda}{\rho|v_i|})_{+}$

If we start with $x_0=(1,1)$, also with $z_0=(1,1)$ and $u_0=(0,0)$ then we have $v_0 = (1,1)$, and the next $x$:

$x^*_i = (1-\frac{\lambda}{\rho})_{+}$

#### Problem III.4.5

By inspection, we see that when $CR = \begin{bmatrix}2 & 1 \\ 0 & 2\end{bmatrix}$, it minimizes the $\|A-CR\|^2_F = 1$. So we can choose $C=\begin{bmatrix}2 & 1 \\ 0 & 2\end{bmatrix}$ and $R=I$

#### Problem III.4.6

Follow example 3, we need minimize $NMF = \|A-X\|^2_F + I_{+}(C) + I_{+}(R)$ with $X=CR$, so we can compute

* $(X_1,C_1) = \text{argmin}\left[\|A-X\|^2_F + \frac{1}{2}\rho\|X-CR_0 + U_0\|^2_F \right] = $ with $X\ge 0, C\ge 0$

Let $C=\begin{bmatrix}c_{11} &c_{12}\\ c_{21} & c_{22}\end{bmatrix}$,$X=\begin{bmatrix}x_{11} &x_{12}\\ x_{21} & x_{22}\end{bmatrix}$, we have 

\begin{align*}
\|A-X\|^2_F + \frac{1}{2\rho}\|X-CR_0 + U_0\|^2_F &= \|\begin{bmatrix}2-x_{11} &1 - x_{12}\\ -1-x_{21} & 2- x_{22}\end{bmatrix}\|^2_F + \frac{1}{2}\rho\|\begin{bmatrix}x_{11}-2c_{11}+1 & x_{12}-c_{12} \\ x_{21} - 2c_{21} & x_{22} - c_{22} + 1\end{bmatrix}\|^2_F \\
&= (2-x_{11})^2 + (1 - x_{12})^2 + (-1-x_{21})^2 + (2- x_{22})^2 + \frac{1}{2}\rho\left((x_{11}-2c_{11}+1)^2 + (x_{12}-c_{12} )^2 + (x_{21} - 2c_{21})^2 + (x_{22} - c_{22} + 1)^2\right)\\
\end{align*}

Now take derivatives w.r.t. to $X, C$, we have

\begin{align*}
\frac{\partial{\text{NMF}}}{\partial{x_{11}}} &= -2(2-x_{11}) + \rho(x_{11}-2c_{11}+1) = (\rho + 2)x_{11} -2\rho c_{11} + \rho -4= 0\\
\frac{\partial{\text{NMF}}}{\partial{x_{12}}} &= -2(1-x_{12})+\rho(x_{12}-c_{12}) = (\rho + 2)x_{12} -\rho c_{12} - 2 = 0\\
\frac{\partial{\text{NMF}}}{\partial{x_{21}}} &=2(1+x_{21}) + \rho(x_{21}-2c_{21}) = (\rho + 2)x_{21} -2\rho c_{21} + 2 = 0\\
\frac{\partial{\text{NMF}}}{\partial{x_{22}}} &= -2(2-x_{22}) + \rho(x_{22}-c_{22}+1) = (\rho + 2)x_{22} -\rho c_{22} + \rho -4 = 0\\
\frac{\partial{\text{NMF}}}{\partial{c_{11}}} &= -2\rho(x_{11}-2c_{11}+1) = 0\\
\frac{\partial{\text{NMF}}}{\partial{c_{12}}} &= -\rho(x_{12}-c_{12}) = 0\\
\frac{\partial{\text{NMF}}}{\partial{c_{21}}} &= -\rho(x_{21}-2c_{21}) = 0\\
\frac{\partial{\text{NMF}}}{\partial{c_{22}}} &= -\rho(x_{22}-c_{22}+1) = 0\\
\end{align*}

Note, we also need satisfy $X\ge 0$ and $C\ge 0$, 
Solve the equations we have $X_1=\begin{bmatrix}2 & 1 \\ 0 & 2 \end{bmatrix}$ and $C_1 = \begin{bmatrix} 1.5 & 1 \\ 0 & 3 \end{bmatrix}$

* Now solve for $R_1 = \text{argmin}\|X_1 - C_1R + U_0\|^2_F$ with $R\ge 0$, that is

\begin{align*}
\|X_1 - C_1R + U_0\|^2_F &= \|\begin{bmatrix}2-1.5R_{11}-R_{21} & 1 - 1.5R_{12}-R_{22} \\ -3R_{21} & 2 - 3R_{22}\end{bmatrix}\|^2_F\\
&= (2-1.5R_{11}-R_{21})^2 + (1 - 1.5R_{12}-R_{22})^2 + (-3R_{21})^2 + (2 - 3R_{22})^2 \\
\end{align*}

Take derivatives w.r.t. $R$, we have 


\begin{align*}
\frac{\partial{}}{\partial{R_{11}}} &= 2(-1.5)(2-1.5R_{11}-R_{21}) = 0\\
\frac{\partial{}}{\partial{R_{12}}} &= 2(-1.5)(1-1.5R_{12}-R_{22}) = 0\\
\frac{\partial{}}{\partial{R_{21}}} &= -2(2-1.5R_{11}-R_{21}) + 18R_{21} = 0 \\
\frac{\partial{}}{\partial{R_{22}}} &= -2(1-1.5R_{12}-R_{22}) -6(2-3R_{22}) = 0\\
\end{align*}

Solve for the equations we have $R=\begin{bmatrix} \frac{4}{3} & \frac{2}{9} \\ 0 & \frac{2}{3} \end{bmatrix} \ge 0$

* Lastly, we have $U_1 = U_0 + X_1 - C_1R_1 = \begin{bmatrix}5 & 1 \\ 0 & 5\end{bmatrix}$

Note $X_1 = C_1R_1 = \begin{bmatrix}2 & 1 \\ 0 & 2\end{bmatrix}$ which is what we have solved in problem 5.

#### Problem III.4.7

We have 

\begin{align*}
\frac{1}{2}\|Ax-b\|^2_2 + \lambda\|x\|_1 &= \frac{1}{2}(4x_1+x_2-1)^2 + \frac{1}{2}(x_2-1)^2 + 2(|x_1|+|x_2|) \\
\end{align*}

Take derivative w.r.t. $x$, we have 

\begin{align*}
\frac{\partial{L}}{\partial{x_1}} &= 4(4x_1 + x_2-1) + 2sign(x_1)x_1 = (8+sign(x_1))x_1 + 2x_2 -2 = 0\\
\frac{\partial{L}}{\partial{x_2}} &= (4x_1 + x_2-1) + (x_2-1) + 2sign(x_2)x_2 = 2x_1 + (1+sign(x_2))x_2 -1 = 0\\
\end{align*}

Solve the equations under different cases with $x_1 \ge 0, x_2 \ge 0$, $x_1 \ge 0, x_2 \lt 0$, $x_1 \lt 0, x_2 \ge 0$, $x_1 \lt 0, x_2 \lt 0$, we found two solutions:

$(x_1, x_2) = (\frac{1}{7}, \frac{5}{14})$ and $(x_1,x_2)= (\frac{1}{2}, -\frac{5}{4})$

Take these solutions back to the Lagrangian function, we found it achieves minimal when $(x_1, x_2) = (\frac{1}{7}, \frac{5}{14})$ where the function has a value about $1.2091836734693877$


#### Problem III.4.8

Note, we have $A^TA = \begin{bmatrix} 16 & 4 \\ 4 & 2 \end{bmatrix}$ and $A^Tb = \begin{bmatrix}4 \\ 2 \end{bmatrix}$

Following Example 4, and use $u_0 = (1,0)=z_0$ with $\rho = 2$, we have

\begin{align*}
x_1 &= (A^TA+\rho I)^{-1}(A^Tb + \rho(z_0 - u_0)) \\
&=(A^TA+\rho I)^{-1}A^Tb \\
&= \begin{bmatrix}16+\rho & 4 \\ 4 & 2 + \rho \end{bmatrix}^{-1} \begin{bmatrix}4 \\ 2 \end{bmatrix} \\
&= \frac{1}{\rho^2 + 18\rho + 16}\begin{bmatrix}2 + \rho & -4 \\ -4 & 16+\rho\end{bmatrix} \begin{bmatrix}4 \\ 2 \end{bmatrix}\\ 
&= \frac{1}{\rho^2 + 18\rho + 16}\begin{bmatrix} 4\rho \\ 2\rho + 16 \end{bmatrix}\\
&= \begin{bmatrix} \frac{1}{7} \\ \frac{5}{14} \end{bmatrix}
\end{align*}

* Now compute $z_1$:
\begin{align*}
z_1 &= S_{\frac{\lambda}{\rho}}(x_1 + u_0) \\
&= sign(x_1+u_0)\max\left(|x_1+u_0|-\frac{\lambda}{\rho}, 0\right)\\
&= sign(\begin{bmatrix} \frac{8}{7} \\ \frac{5}{14} \end{bmatrix})\max\left(|\begin{bmatrix} \frac{8}{7} \\ \frac{5}{14} \end{bmatrix}|-1, 0\right)\\
&= \max\left(\begin{bmatrix} \frac{8}{7} \\ \frac{5}{14} \end{bmatrix} -1, 0\right)\\
&= \max\left(\begin{bmatrix} \frac{1}{7} \\ -\frac{9}{14} \end{bmatrix}, 0\right)\\
&= \begin{bmatrix} \frac{1}{7} \\ 0 \end{bmatrix}
\end{align*}

* And we have $u_1 = u_0 + x_1 - z_1 = \begin{bmatrix} 1 \\ \frac{5}{14} \end{bmatrix}$

#### Problem III.4.9

Let $L = \frac{1}{2}\|x\|^2 + \frac{1}{2}\|x-v\|^2 = \frac{1}{2} x^Tx + \frac{1}{2} (x-v)^T(x-v)$, take derivative w.r.t. $x$, we have

\begin{align*}
\frac{\partial{L}}{\partial{x}} &= x + x-v\\
&= 2x-v\\
\end{align*}

Let the derivative equal to 0, we see $\text{Prox}_F(v) = \text{argmin}L = \frac{v}{2}$ 

#### Problem III.4.10 TODO


* If $u(x,y) = x+y$, we have $\int \int_{x,y \text{ in triangle}} \|grad u\|_2 dx dy = \int \int_{x,y \text{ in triangle}}\|(1,1)\|_2dxdy = \int \int_{x,y \text{ in triangle}}\sqrt{2} dxdy =\sqrt{2} \int \int_{x,y \text{ in triangle}}dxdy = \frac{\sqrt{2}}{2}$ 

Using the right hand side, we have if $u(x,y)=t$, which is a line segment within the triangle. It has length of $\sqrt{t^2+t^2}=\sqrt{2}t$ within the triangle. So $\int^1_0 \sqrt{2}tdt = \sqrt{2}\int^1_0t dt = \frac{\sqrt{2}}{2}$

* If $u=0$ in a unit square and $u=1$ outside, $t$ can only be 0 or 1. If $t=0$, the length is 4, the length of the unit square. if $t=1$, $u=1$ is a plane with middle part missing. its length is infity because the $u$ here has domain on the whole $x,y$ plane. So $\|u\|_{BV}=\infty$. Not sure if this is correct though?

#### Problem III.5.1

* Let $A_0 = \begin{bmatrix} 1 & 2 \\ a & b \end{bmatrix}$, let $\lambda_1, \lambda_2$ be the eigenvalues of $A^T_0A_0 = \begin{bmatrix} 1+a^2 & 2+ab \\ 2+ab & 4+b^2 \end{bmatrix}$, so we have $\lambda_1 + \lambda_2 = 1+a^2 + 4 + b^2 = 5 + a^2 + b^2$ and $\lambda_1\lambda_2 = (1+a^2)(4+b^2) - (2+ab)^2 = (2a-b)^2$. 

The singular values of $A_0$ are thus $\sigma_1 = \sqrt{\lambda_1}, \sigma_2 = \sqrt{\lambda_2}$

$\|A_0\|^2_N = (\sigma_1 + \sigma_2)^2 = \sigma^2_1 + \sigma^2_2 + 2\sigma_1\sigma_2 = \lambda_1 + \lambda_2 + 2\sqrt{\lambda_1 \lambda_2} = 5 + a^2 + b^2 + 2\sqrt{(2a-b)^2} = 5 + a^2 + b^2 + 2|2a-b|$

This equals to $(a+2)^2 + (b-1)^2$ when $2a-b>0$ and $(a-2)^2+(b+1)^2$ when $2a-b <=0$

They achieve minimum of 5 when $a=b=0$, so

$A_0 = \begin{bmatrix} 1 & 2 \\0 & 0 \end{bmatrix}$ minimizes $\|A_0\|_N$

* Let $B_0 = \begin{bmatrix} 1 & a \\ b & 4 \end{bmatrix}$, let $\lambda_1, \lambda_2$ be the eigenvalues of $B^T_0B_0 = \begin{bmatrix} 1+b^2 & a+4b \\ a+4b & 16+a^2 \end{bmatrix}$, so we have $\lambda_1 + \lambda_2 = 1+b^2 + 16 + a^2 = 17 + a^2 + b^2$ and $\lambda_1\lambda_2 = (1+b^2)(16+a^2)-(a+4b)^2= (ab-4)^2$. 

$\|B_0\|^2_N = (\sigma_1 + \sigma_2)^2 = \sigma^2_1 + \sigma^2_2 + 2\sigma_1\sigma_2 = \lambda_1 + \lambda_2 + 2\sqrt{\lambda_1 \lambda_2} = 17 + a^2 + b^2 + 2\sqrt{ (ab-4)^2} = a^2+b^2 + 2|ab-4| + 17$

This equals to $(a+b)^2 + 9$ when $ab > 4$ and $(a-b)^2 + 25 $ when $ab <=4$. 
The second achieves minimal of 25 when $a=b=0$. We want to check whether there are $a,b$ that can make the first one less than 25 when $ab > 4$, so we check $(a+b)^2 + 9 < 25$, and we find it requires $(b-2)^2 < 0$ or $(b+2)^2 < 0$, which is impossible. 
But on the boundary, we see that $a=b=2$ or $a=b=-2$ also achieves the same minimum 25. 

So $B_0 = \begin{bmatrix} 1 & a \\a & 4 \end{bmatrix}$ minimizes $\|B_0\|_N$, where $a=0,2,-2$.

* Let $C_0 = \begin{bmatrix} 1 & 2 \\ 3 & a \end{bmatrix}$, let $\lambda_1, \lambda_2$ be the eigenvalues of $C^T_0C_0 = \begin{bmatrix} 10 & 2+3a \\ 2+3a & 4+a^2 \end{bmatrix}$, so we have $\lambda_1 + \lambda_2 = 14 + a^2$ and $\lambda_1\lambda_2 = 10(4+a^2) -(2+3a)^2 = (a-6)^2$. 

$\|C_0\|^2_N = (\sigma_1 + \sigma_2)^2 = \sigma^2_1 + \sigma^2_2 + 2\sigma_1\sigma_2 = \lambda_1 + \lambda_2 + 2\sqrt{\lambda_1 \lambda_2} = 14 + a^2 + 2\sqrt{(a-6)^2} = 14 + a^2 + 2|a-6|$.

Take derivative w.r.t. $a$, we find $a=1$, so $C_0 = \begin{bmatrix} 1 & 2 \\3 & 1 \end{bmatrix}$ minimizes $\|C_0\|_N$


#### Problem III.5.2

From the equation we have 
\begin{align*}
3a+4b &= 1\\
3c+4d &= 0 \\
\end{align*}

To find the matrix with smallest "sum norm" $\|A\|_S = |a|+|b|+|c|+|d|$, since $a,b$ and $c,d$ are kind of independent of each other in terms of constraints. So we can find the minimum of $|a|+|b|$ and $|c|+|d|$ separately. 

First notice, that since $3c+4d=0$, according to the figure I.16, this line will always cross the diamond generated by $|c|+|d| \le t$ regardless of the value of $t$. so the minimum value of $|c|+|d|$ is 0 when $c=d=0$.

For $3a+4b=1$, this line has intercepts with $a$-axis at $\frac{1}{3}$, and intercept with $b$-axis at $\frac{1}{4}$. 
Imagine the diamond generated by $|a|+|b| \le t$ gradually expands as $t$ increases from 0. It will first touch the intercept with $b$-axis at $\frac{1}{4}$, so the minimum of $|a|+|b|=\frac{1}{4}$ when $a=0,b=\frac{1}{4}$.


#### Problem III.5.3

For the unit ball $\|A\|_S \le 1$, it's a 4-dimensional unit ball with axis $a,b,c,d$. It's actually a diamond in 4-dimension. 


#### Problem III.5.4 TODO


#### Problem III.5.5 TODO

* If only one entry of a matrix $A$ is unknown, to minimize $\|A\|_S$, I'll put 0 in the missing entry. 
* To minimize $\|A\|_N$, think about $S=A^TA$, the eigenvalues of matrix $S$ are $\lambda_i$, $i=1,\dots,r$. All $\lambda_i \ge 0$ because $S$ is positive semidefinite. 

On the other hand, we have $\|A\|_N = \sum_i \sigma_i$, to minimize $\|A\|_N$ is the same as to minimize $\|A\|^2_N = \sum\sigma^2_i + \sum_{i\ne j} \sigma_i \sigma_j$

Notice $\sum\sigma^2_i = \sum \lambda_i =  \text{trace}(A^TA) = \sum a^T_ia_i$, where $a_i$ are the columns for matrix $A$. It's easy to see that if there's only one entry missing in one of the $a_i$s, it's better to make it zero to minimize the sum of $\lambda_i$.

I am not sure how to prove the part with $\sigma_i\sigma_j$ though. 

#### Problem III.5.6

$U^* = U\Sigma^{\frac{1}{2}}=U\Sigma^{\frac{1}{2}}I$, which is the SVD of matrix $U^*$, and its singular values are the entries in $\Sigma^{\frac{1}{2}}$, thus we have its eigenvalues as entries in $\Sigma$. $\|U^*\|^2_F = \sum^r_{i=1} \lambda_i$, i.e. the sum of entries in matrix $\Sigma$.

However, on the other side, $\|A\|_N$ is the sum of its singular values, which are the entries of $\Sigma$ according to its SVD. 

This proves that $\|U^*\|^2_F = \|A\|_N$. Similarly we have $\|V^*\|^2_F = \|A\|_N$.

#### Problem III.5.7

If $A$ is positive semidefinite, then we can write $A=Q\Lambda Q^T$, trace of $A$ equals to the sum of its eigenvalues. We have $A^TA = Q\Lambda^2Q^T$, so the singular values of $A$ equal to its eigenvalues (because $A$ is positive semidefinite, all its eigenvalues are larger than or equal to 0). $\|A\|_N$ equals to the sum of its singular values, which is also sum of its eigenvalues, which is the trace of $A$.

If $A=UV$, then we have

\begin{align*}
\text{trace}(UV) &= \sum_i\sum_j U_{ij}V_{ji} \\
&\le \sum_i |\sum_jU_{ij}V_{ji}| \\
&\le \sum_i\sum_k |\sum_jU_{ij}V_{jk}| \\
&= \|UV\|_F \\
&\le \|U\|_F\|V\|_F \\
\end{align*}

Where the last inequality comes from equation (13) in I.11 on page 92.

In [7]:
import numpy as np
S=np.identity(2)
Z = np.array([[0, 2-3.0j], [-2+3j, 0]])
A = S+Z
Ac = np.conj(A)
np.matmul(A, Ac)

array([[-12.+0.j,   4.+0.j],
       [ -4.+0.j, -12.+0.j]])

In [8]:
np.matmul(Ac, A)

array([[-12.+0.j,   4.+0.j],
       [ -4.+0.j, -12.+0.j]])

In [9]:
np.matmul(S, S)

array([[1., 0.],
       [0., 1.]])

In [10]:
np.matmul(S, Z)

array([[ 0.+0.j,  2.-3.j],
       [-2.+3.j,  0.+0.j]])

In [11]:
np.matmul(np.conj(Z), S)

array([[ 0.+0.j,  2.+3.j],
       [-2.-3.j,  0.+0.j]])

In [12]:
np.matmul(np.conj(Z), Z)

array([[-13.+0.j,   0.+0.j],
       [  0.+0.j, -13.+0.j]])

In [13]:
np.matmul(S, np.conj(Z))

array([[ 0.+0.j,  2.+3.j],
       [-2.-3.j,  0.+0.j]])

In [14]:
np.matmul(Z, np.conj(Z))

array([[-13.+0.j,   0.+0.j],
       [  0.+0.j, -13.+0.j]])

In [15]:
np.matmul(Z, np.conj(S))

array([[ 0.+0.j,  2.-3.j],
       [-2.+3.j,  0.+0.j]])